[package]
name = "splittable-random"
version = "0.1.0"
authors = ["Chris <98064596+puzzledBox@users.noreply.github.com>"]
edition = "2021"
publish = false

[dependencies]
fnv = "1.0.7"
rand = "0.8.4"
rand_xoshiro = "0.6.0"
